services:
  lgtm:
    image: grafana/otel-lgtm:0.9.2
    container_name: otel-lgtm-test
    ports:
      - "3000:3000"   # Grafana
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    healthcheck:
      # LGTM writes /tmp/ready when fully started; wget/curl are unreliable in this image
      test: ["CMD-SHELL", "test -f /tmp/ready"]
      interval: 5s
      timeout: 2s
      retries: 60

  control-plane:
    build:
      context: .
      dockerfile: ./gados-control-plane/Dockerfile
    depends_on:
      lgtm:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - OTEL_SERVICE_NAME=gados-control-plane
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=gados,deployment.environment=test
      - LOG_LEVEL=INFO
      # Keep agent bus state ephemeral in container
      - GADOS_RUNTIME_DIR=/tmp/gados-runtime
    healthcheck:
      # Python is guaranteed to exist; safer than wget/curl
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()\""]
      interval: 5s
      timeout: 2s
      retries: 30
    command:
      - uvicorn
      - gados_control_plane.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
